modLoader="javafml"
loaderVersion="[34,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/GooglyEyes/issues"

[[mods]]
    modId="themasks2020"
    version="${file.jarVersion}" #mandatory
    displayName="The Masks202"
    displayURL="http://ichun.me/"
    authors="TamasHenning, iChun, artdude543"
    description='''
    Because why not? Definitely Yes
    '''

[[dependencies.googlyeyes]]
    modId="ichunutil"
    mandatory=true
    versionRange="[10.0.0,11)"
    ordering="NONE"
    side="BOTH"
